
volumes:
  foodgram_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data

  backend:
    build: ./backend/foodgram/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
      #- ./backend/foodgram:/app
    

  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      # - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine
    env_file: .env
    ports:
      #- 8001:80
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/
      
